---
fail_fast: true
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb=500]
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: no-commit-to-branch
            stages: [commit]
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 2.1.5
      hooks:
          - id: forbid-binary
            exclude: |
                (?x)^(
                    rsc/.*\.(png|jpg|gif)
                )$
          - id: markdownlint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://gitlab.com/PyCQA/flake8
      rev: 3.9.0
      hooks:
          - id: flake8
    - repo: https://github.com/PyCQA/isort
      rev: 5.7.0
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: local
      hooks:
          - id: pytest-cov
            name: Launch tests with Pytest
            stages: [commit]
            language: system
            entry: poetry run pytest --cov --cov-fail-under=100 --cov-report term-missing
            types: [python]
            pass_filenames: false
